apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xblobs.infrastructure.example.org
spec:
  group: infrastructure.example.org
  names:
    kind: XBlob
    plural: xblobs
  claimNames:
    kind: Blob
    plural: blobs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: "ID of this Blob that objects will use to refer to it."
                  minLength: 1
                  # Maximum key length in GCP is 40 characters. We are setting a 34 character
                  # limit to accomodate the generated hash suffix ('-' + 5 chars).
                  maxLength: 34
                parameters:
                  type: object
                  description: "Blob parameters."
                  properties:
                    resourcegroup:
                      type: string
                      description: "ID of a resource group to associate the blob with. Will create one with this name if not exists."
              required:
                - id
                - parameters
            status:
              type: object
              properties:
                subnetIds:
                  type: array
                  items:
                    type: string