apiVersion:  apps/v1
kind: ReplicaSet
metadata:
  name: test
spec:
  replicas: 4
  selector:
    matchLabels:
      type: backend
      service: test
  template:
    metadata:
      labels:
        type: backend
        service: test
        db: mongo
        language: go
    spec:
      containers:
      - name: db
        image: mongo:3.3
      - name: api
        image: vfarcic/test
        env:
        - name: DB
          value: localhost
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080